dependencies {
  // 直接引用 JAR 文件
  implementation files(System.getProperty('user.home') + '/.m2/repository/systems/comodal/json-iterator/2.13.0/json-iterator-2.13.0.jar')
  implementation project(':core')
}

configurations.all {
  resolutionStrategy {
    // 配置依赖解析策略
    failOnVersionConflict()
  }
  
  // 忽略 JVM 版本兼容性检查
  attributes.attribute(org.gradle.api.attributes.java.TargetJvmVersion.TARGET_JVM_VERSION_ATTRIBUTE, 17)
}

// 配置编译选项
tasks.withType(JavaCompile).configureEach {
  options.compilerArgs << '--release' << '17'
  options.fork = true
}

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(17)
  }
}

// 为验证启用--system属性
gradle.taskGraph.whenReady {
  System.setProperty('org.gradle.dependency.verification', 'off')
  System.setProperty('org.gradle.configuration-cache', 'false')
}

repositories {
  mavenLocal() // 使用本地 Maven 仓库
}