plugins {
  alias(libs.plugins.jlink)
}

apply(plugin: 'org.beryx.jlink')

dependencies {
  // 直接引用 JAR 文件
  implementation files(System.getProperty('user.home') + '/.m2/repository/systems/comodal/json-iterator/2.13.0/json-iterator-2.13.0.jar')
  implementation project(':core')
}

afterEvaluate {
  jlink {
    imageName.set(project.name)
    options.addAll(List.of(
        '--bind-services',
        '--no-man-pages',
        '--vm=server',
        '--ignore-signing-information'
    ))
    enableCds()
  }
}
